server:
  port: 8088


#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml    #mybatis配置文件所在路径
#  type-aliases-package: com.edu.zut.itassociation.entities               #所有Entity别名类所在包
#  mapper-locations: classpath:mybatis/mapper/**/*.xml                  #mapper映射文件路径



spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.96.228.41:3306/itassociation?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                      #数据库连接池最小连接数
      initial-size: 5                                  #初始化连接数
      max-total: 5                                     #最大连接数
      max-wait-millis: 200                             #等待连接获取的最大超时时间
    devtools:
      restart:
        enabled: true                                    #开启热部署



#mybatis-plus 日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)