#服务端口
server:
  port: 8001

spring:
  application:
    name: user-teacher   #服务名称
  profiles:
    active: dev   #开发环境配置
  jackson:
#    设置时间展示格式和时区
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.228.41:3306/itassociation?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                      #数据库连接池最小连接数
      initial-size: 5                                  #初始化连接数
      max-total: 5                                     #最大连接数
      max-wait-millis: 200                             #等待连接获取的最大超时时间
    devtools:
      restart:
        enabled: true                                    #开启热部署




  #    逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#设置日志级别
#logging:
#  level:
#    root: INFO


#mybatis-plus 日志配置
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl